### ISSUE TITLE
Enhance the UI responsiveness

### ISSUE THREAD

**Issue by its-ayush-07** [Portfolio-Shop/portfolioshop#115]
**Is your feature request related to a problem? Please describe.**
Some components of the UI are not completely mobile and tablet responsive.

**Describe the solution you'd like**
I'd like to enhance the responsiveness of the UI by properly spacing some of the buttons and components in the attached screenshots.

**Additional context**

<img src="https://user-images.githubusercontent.com/74665996/183587328-08670c1e-8715-44dc-b289-a4fec8a0503a.png" width="300" /> &nbsp; <img src="https://user-images.githubusercontent.com/74665996/183587326-d898dde3-fc84-4462-a5b6-68f2e1590d1b.png" width="200" />

**Comment by sudip-mondal-2002** [comment]
@its-ayush-07 you may work on it, I have assigned you.
