### ISSUE TITLE
Enhancing the UI of the website

### ISSUE THREAD

**Issue by vandana3869** [Portfolio-Shop/portfolioshop#122]
**Describe the solution you'd like**
https://sukoon.my.canva.site/dark-blue-and-purple-bold-tech-app-business-website this my idea for the UI

**Comment by sudip-mondal-2002** [comment]
Hey @vandana3869 I'll assign this to you. You may work on the issue.

**Comment by sudip-mondal-2002** [comment]
Duplicate #36
