### ISSUE TITLE
Improve MenuBar button

### ISSUE THREAD

**Issue by advait-cs** [Portfolio-Shop/portfolioshop#125]
**Is your feature request related to a problem? Please describe.**
  After clicking on the "Source" button in MenuBar it is displaying the error page.

**Describe the solution you'd like**
After clicking on the "Source" button, it can be redirected to the [(GitHub link)](https://github.com/Portfolio-Shop/portfolioshop) in a separate tab.

![portshop](https://user-images.githubusercontent.com/76991036/187122149-72e99a34-986b-491c-81d8-47538276f308.png)

I would like to work on this issue, Can you please assign me?

**Comment by sudip-mondal-2002** [comment]
@advait-cs I've assigned you this issue.
