### ISSUE TITLE
Razorpay Donate Now Button not Scaling on Mobile

### ISSUE THREAD

**Issue by kunalagra** [Portfolio-Shop/portfolioshop#127]
**Describe the bug**
Donate Now button not scaling on mobile

**To Reproduce**
1. Go to website on mobile

**Expected behavior**
The Donate now button is either hidden or scaled down to fit properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/66416646/187219538-e266faee-680a-4eaf-8718-28f4a78fd64d.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12
 - Browser: Chrome
 - Version: 104

**Comment by sudip-mondal-2002** [comment]
@kunalagra Do you want to work on this issue?

**Comment by kunalagra** [comment]
> @kunalagra Do you want to work on this issue?

Yes. I would like to work on this issue

**Comment by sudip-mondal-2002** [comment]
@kunalagra I've assigned you
