### ISSUE TITLE
Linkedin Button is not working 

### ISSUE THREAD

**Issue by itsprathapkreddy** [Portfolio-Shop/portfolioshop#134]
**Describe the bug**
The Footer of the website has a LinkedIn button, which is forwarding to a 404 page.

**To Reproduce**
1. Go to footer
2. Click on LinkedIn Button

**Expected behavior**
Remove the LinkedIn button or point it to a page saying we will be on LinkedIn soon.
I personally prefer the second option.

**Desktop
 - OS: All
 - Browser All
 - Version All

**Smartphone
 - Device: All
 - OS: All
 - Browser All
 - Version All
 
I would like to work on it if you can assign it to me :)

**Comment by sudip-mondal-2002** [comment]
We will assign only one issue at a time. Please complete the other one first. Thanks :)

**Comment by kunalranjan19** [comment]
hey can you Assign this to me

**Comment by kunalranjan19** [comment]
@sudip-mondal-2002

**Comment by Himanxu1** [comment]
assign this to me

**Comment by Himanxu1** [comment]
@sudip-mondal-2002

**Comment by ayush-tiwari26** [comment]
Hey @Himanxu1, we are right now assigning only one issue at a time, please try to wrap that up and then I will assign this to you.

**Comment by arun-kushwaha04** [comment]
@sudip-mondal-2002 can I work on this issue ?

**Comment by sudip-mondal-2002** [comment]
@arun-kushwaha04 sure please proceed, I've assigned you this issue
