### ISSUE TITLE
Add option to download portfolio as an HTML file

### ISSUE THREAD

**Issue by sudip-mondal-2002** [Portfolio-Shop/portfolioshop#146]
It'd be nice if people can download the HTML directly from the website.

Create a button and allow downloading the HTML for the portfolio

**Comment by arun-kushwaha04** [comment]
@sudip-mondal-2002 can I work on this feature ?

**Comment by sudip-mondal-2002** [comment]
Sure, I have assigned you this issue, please follow the contribution guidelines.

**Comment by arun-kushwaha04** [comment]
@sudip-mondal-2002 i am able to get google auth option when running locally.
![image](https://user-images.githubusercontent.com/73020364/193651507-efdeb679-53fc-4720-bfed-5892a754e29f.png)

**Comment by sudip-mondal-2002** [comment]
@arun-kushwaha04 you need to add a google auth client id in the file local.settings.json of API folder key should be REACT_APP_GOOGLE_AUTH_CLIENT_ID. Otherwise, run the setup.sh file to get the file created, or optionally use vscode remote containers or codespaces to get an already setup device.

**Comment by arun-kushwaha04** [comment]
@sudip-mondal-2002 I ran setup.sh . But I think this is not the issue. The react app is not able to acces the api server, may be they are running on different port (3000 for react and 7071 for api , though not sure of this part).


![image](https://user-images.githubusercontent.com/73020364/193655504-1d837d85-f697-4215-92d2-4741fe046665.png)

**Comment by sudip-mondal-2002** [comment]
You need to run npm start at the root level of the project, it'll run the API server and client server simultaneously and both will be proxid from `localhost:4280`. So in order to access the server from your client your web app should be opened at `localhost:4280` and not `localhost:3000`

**Comment by arun-kushwaha04** [comment]
Ok got it working, thanks for help.
