### ISSUE TITLE
Social media icons are visible even if the URLs are not provided

### ISSUE THREAD

**Issue by roopeshsn** [Portfolio-Shop/portfolioshop#152]
**Describe the bug**
To create a portfolio website under the "User Details" there are fields to enter the "Social Handles" URL. Though, if the links are not given for some of the social accounts the website is displaying the respective social media icon. In my case, I have given only Twitter, Linkedin, and GitHub URLs. But on the website, the Facebook and Instagram icons are also visible. Similar behavior in the footer too.

**To Reproduce**
1. Go to the website creation page [https://www.portfolioshop.tech/](url)
2. Give the "Social Handles" URL which is under "User Details"
3. Save the changes and click the "VISIT YOUR WEBSITE" button
4. See the icons in the Hero section

**Expected behavior**
It only renders the icon for the URLs provided

**Screenshots**
![portfolio_shop_social_handles](https://user-images.githubusercontent.com/70762571/193445069-61065359-ac87-499a-b884-93adb455ca03.png)

![porfolio_shop_homepage](https://user-images.githubusercontent.com/70762571/193445061-30adffe3-74d8-489c-944a-036d01845e40.png)

![portfolio_shop_footer](https://user-images.githubusercontent.com/70762571/193445347-ccb2aec4-dcc8-426b-8d94-264842342c9f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 106

**Smartphone (please complete the following information):**
 - Device: _No response_
 - OS: _No response_
 - Browser: _No response_
 - Version: _No response_

**Additional context**
_No response_

**Comment by ayush-tiwari26** [comment]
Duplicate Issue, #48
