### ISSUE TITLE
Fix the errors in console

### ISSUE THREAD

**Issue by sudip-mondal-2002** [Portfolio-Shop/portfolioshop#45]
**Describe the bug**
On starting the react app, some errors show up in the console. Fix that issue.

**Comment by deeola** [comment]
Hello, is it possible to add a screenshot of these errors?

**Comment by Joiyad** [comment]
I am interested in fixing this issue, can you assign me this issue?

**Comment by ayush-tiwari26** [comment]
Hey @Joiyad, I am assigning you the issue.
Be sure to have a look at contribution guidelines.
WIsh you luck.
