### ISSUE TITLE
Update Secuirity.md

### ISSUE THREAD

**Issue by sudip-mondal-2002** [Portfolio-Shop/portfolioshop#51]
Go through the codebase and update the security.md file.

**Comment by Ahad1317** [comment]
Hey there ! Can I work on this.. I would like to update the security.md file..

**Comment by sudip-mondal-2002** [comment]
We'll assign one issue to one coordinator at a time

**Comment by abhilipsasahoo03** [comment]
Hi @sudip-mondal-2002 is there any chance I could work on this issue under hacktoberfest? I can't seem to find any issue labelled as such.

**Comment by sudip-mondal-2002** [comment]
Sure you can work on this, we'll label your pull request under hacktoberfest

**Comment by abhilipsasahoo03** [comment]
Hi @sudip-mondal-2002 can you provide some insight on what points I can include in the Security.md file. Can I include disclosure policy, or response time after receiving a report, or some other points that I maybe am missing out? If so, can you expand on that?

**Comment by sudip-mondal-2002** [comment]
Yeah please add the disclosure policy, don't put any response time as such,  you can put any other security related topics.
