### ISSUE TITLE
Fix Security vulnerability from npm audit

### ISSUE THREAD

**Issue by sudip-mondal-2002** [Portfolio-Shop/portfolioshop#52]
**Describe the bug**

**To Reproduce**
1. Go to root directory of the project
2. Run 'npm audit'
3. See error

**Expected behavior**
There should be 0 vulnerabilities

**Additional context**
npm audit fix won't help. It needs manual reviews

**Comment by its-ayush-07** [comment]
@sudip-mondal-2002  I am interested to work on this issue.

![Screenshot (25)](https://user-images.githubusercontent.com/74665996/194940590-0400961d-d175-4622-8d26-bdddfdbaae99.png)

After manually reviewing, I found that upgrading the npm version from "^6.14.16" to "^8.19.2", fixes 12 out of 13 vulnerabilities, as you can see in the above screenshot. Also, it is not a breaking change as the application runs smoothly after the upgrade.

So, shall I open a PR with the above changes?

**Comment by sudip-mondal-2002** [comment]
after updating npm version have you checked if the project is running? i don't think so.

**Comment by its-ayush-07** [comment]
> after updating npm version have you checked if the project is running? i don't think so.

Yes, I ran the following in the root directory after updating the version:
`npm run dev-install`
`npm start`

and the project is running fine.

**Comment by sudip-mondal-2002** [comment]
have you updated npm version in all the folders? root directory, api and app?

**Comment by its-ayush-07** [comment]
> have you updated npm version in all the folders? root directory, api and app?

![Screenshot (26)](https://user-images.githubusercontent.com/74665996/195169005-bc523bac-921f-46f8-89f5-b58e325d4de3.png)

Yes, I've updated it in all the folders and it works fine. Still, you can check it in your local system to verify.

**Comment by sudip-mondal-2002** [comment]
ok please create a pull request.
