### ISSUE TITLE
Optimize the SEO

### ISSUE THREAD

**Issue by sudip-mondal-2002** [Portfolio-Shop/portfolioshop#53]
Find and fix the issues with the SEO compatibility of the website.

**Comment by Oyedare** [comment]
For a starter, i would love to work on this issue.

**Comment by sudip-mondal-2002** [comment]
Hey @Oyedare! Glad you want to work on this issue. I'll assign you this issue. Let me know an estimated time by when you'll submit a pull request.

All the best.

**Comment by Oyedare** [comment]
What node version is this project built on. I'm asking because there's an error occurring when trying to install the dependencies

**Comment by sudip-mondal-2002** [comment]
node 14.19.1
npm 6.14.16

**Comment by Oyedare** [comment]
I'm having issues installing dependencies, it's trying to install Azure function core tools and it's taking so long to install. I would share a screenshot of the installation.
![Screenshot (8)](https://user-images.githubusercontent.com/59839603/165838812-be934eaf-0d62-4690-b7d4-504b89536f0e.png)
