### ISSUE TITLE
Render a loading prompt

### ISSUE THREAD

**Issue by sudip-mondal-2002** [Portfolio-Shop/portfolioshop#59]
**Describe the bug**
When the API is called to fetch the user data for the dashboard, there should be a loading screen while it's fetching it.

Add a loading screen/prompt/snackbar while fetching the data

**Comment by deeola** [comment]
Hello, can I work on this?

**Comment by sudip-mondal-2002** [comment]
Yes sure, I'll assign it to you. Can you put an estimated date by which you'll be submitting a PR?

**Comment by deeola** [comment]
So, before I give a date. I need to be clear about the task. 

If you check https://deeola.github.io/newPortfolio/ (work in progress), there is a loader that comes in before the component renders, that is what you want, right?

**Comment by sudip-mondal-2002** [comment]
Yes, just match the theme with ours.

**Comment by deeola** [comment]
Alright, I'll submit a PR in two days. I don't know if I have to work on figma for the graphics. If not, a day.

**Comment by deeola** [comment]
Hello, I am finding it difficult to start the api. 

<img width="1006" alt="Screenshot 2022-05-03 at 09 46 43" src="https://user-images.githubusercontent.com/71495600/166420644-0b58385e-5190-4132-9957-0a6d6bda6821.png">

**Comment by sudip-mondal-2002** [comment]
Hi @deeola We have used node 14.19.1 for the website. I think that's the issue with your version.

**Comment by deeola** [comment]
Yeah, I figured that was the problem. Any pointer on how to solve this?

**Comment by sudip-mondal-2002** [comment]
You may use node version manager to switch versions in between https://github.com/nvm-sh/nvm

**Comment by sudip-mondal-2002** [comment]
Any updates @deeola ?

**Comment by sudip-mondal-2002** [comment]
I am unassigning you @deeola

**Comment by its-ayush-07** [comment]
Can I work on this issue?
Also, can you please share the `REACT_APP_GOOGLE_AUTH_CLIENT_ID` environment variable? Without this, the `GoogleLoginComp` component is not getting rendered and I cannot access the Dashboard.

**Comment by sudip-mondal-2002** [comment]
You need to create your own, or check the dev.sh file there will be one test key ig.

**Comment by its-ayush-07** [comment]
Yes, I found one test key. Thank you.
Can I work on this issue under SSOC?

**Comment by sudip-mondal-2002** [comment]
@its-ayush-07 I've assigned you
