### ISSUE TITLE
Create a 404 page

### ISSUE THREAD

**Issue by sudip-mondal-2002** [Portfolio-Shop/portfolioshop#65]
**Is your feature request related to a problem? Please describe.**
We don't have a 404 page yet. Would love to have one

**Describe the solution you'd like**
Please design and code a 404 page. Or you may create a design and put a screenshot here. If someone else like he/she could code it.

**Comment by gautamV19** [comment]
![404-error-template-18](https://user-images.githubusercontent.com/86219774/166406656-319e3e20-4240-4f04-b580-45c2470737a7.png)
 Can I build a 404 page like this?

**Comment by sudip-mondal-2002** [comment]
Sure @gautamV19 will assign this issue to you.

**Comment by sudip-mondal-2002** [comment]
As there isn't a response since a long time, I'm going to unassign you from this issue @gautamV19

**Comment by NabajitS** [comment]
I can get working on it. Can I get this issue?

**Comment by sudip-mondal-2002** [comment]
@NabajitS I've assigned you this issue.

**Comment by NabajitS** [comment]
Should I push the commits and create a PR or do you have a branch naming convention?

**Comment by sudip-mondal-2002** [comment]
We don't have a naming convention for branches, put all small letters without spaces(you may use -) while naming a branch.
