### ISSUE TITLE
Update the Image Upload UI

### ISSUE THREAD

**Issue by sudip-mondal-2002** [Portfolio-Shop/portfolioshop#67]
**Is your feature request related to a problem? Please describe.**
The UI of the upload Image component is a bit messy

**Describe the solution you'd like**
Make the height and width of the image upload component constant (30 units) and make the original image visible on hover like a tooltip. You may suggest your own idea also.

**Comment by Joiyad** [comment]
I am interested in fixing this issue, please assign me.

**Comment by sudip-mondal-2002** [comment]
@Joiyad ,I have assigned you this issue.
