### ISSUE TITLE
Add all contributors to teams page

### ISSUE THREAD

**Issue by sudip-mondal-2002** [Portfolio-Shop/portfolioshop#68]
**Is your feature request related to a problem? Please describe.**
Currently, only repo maintainers are added to the team's page statically.

**Describe the solution you'd like**
Along with the statically rendered maintainers we want to render all the contributors dynamically.
You may use https://contrib.rocks/image?repo=Portfolio-Shop/portfolioshop this image or any other alternative.

**Comment by its-ayush-07** [comment]
Can I work on this issue?

**Comment by sudip-mondal-2002** [comment]
I have assigned it to you, get it done fast.
