### ISSUE TITLE
Add a snackbar on save

### ISSUE THREAD

**Issue by sudip-mondal-2002** [Portfolio-Shop/portfolioshop#70]
**Is your feature request related to a problem? Please describe.**
Currently, an alert box appears on save success or failure in the dashboard.

**Describe the solution you'd like**
Show the snackbar instead of alert dialogue in there.

**Comment by YashDalal11** [comment]
Hi, can I get this issue?

**Comment by sudip-mondal-2002** [comment]
Hi @YashDalal11, I've assigned you this issue, please let me know if you face any issue

**Comment by YashDalal11** [comment]
sure

**Comment by its-ayush-07** [comment]
Hello, can I work on this issue under SSOC?

**Comment by sudip-mondal-2002** [comment]
@its-ayush-07 it's already assigned to someone else

**Comment by its-ayush-07** [comment]
@sudip-mondal-2002 can I work on this issue now, as it has been inactive for a long time?

**Comment by sudip-mondal-2002** [comment]
Sure, Please go on
