### ISSUE TITLE
Add LEARN.md

### ISSUE THREAD

**Issue by ericdrosado** [Portfolio-Shop/portfolioshop#85]
`Learn` repos should have a LEARN.md file to teach another student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn. 

If your project is very large, consider just teaching a certain tool or implementation that your project utilizes.

**Comment by sudip-mondal-2002** [comment]
Hi @ericdrosado sir, I have already covered these in the [CONTRIBUTING.md](https://github.com/Portfolio-Shop/portfolioshop/blob/master/CONTRIBUTING.md). So, how should I proceed now? Should I split the content?

**Comment by sudip-mondal-2002** [comment]
@ericdrosado sir, I have completed this. Please have a look in the file and let me know if any further changes needed.

**Comment by ericdrosado** [comment]
@sudip-mondal-2002 The information you added to `LEARN.md` is super helpful, however when I say "build," I'm referring to how you coded the project so someone could make a project like yours. 

Looking over your code, there are a lot of moving pieces, and it may be time consuming to outline all of the components step by step. You are more than welcome to identify a component of your project that might be helpful to teach a learner so you don't have to teach a student how to code everything. 

You are always welcome to change your focus to a `collaborate` repo instead of a `collaborate + learn` repo if you do not have the time to develop a lesson.

**Comment by sudip-mondal-2002** [comment]
@ericdrosado  Sir, it's hard to explain the things everything from scratch. We'd like to change the focus to collaborate then.
