### ISSUE TITLE
Add Topics

### ISSUE THREAD

**Issue by ericdrosado** [Portfolio-Shop/portfolioshop#86]
In Community Exchange, GitHub Topics will help the discoverability of your project. You already have some great topics on your repo! 

If you happen to use any offers from the GitHub Student Developer Pack to build your project, I would recommend adding the company names to increase discoverability. If you did not, feel free to close this issue.

**Comment by sudip-mondal-2002** [comment]
I had already added most of the topics. Now, I have added a few more numbers of them. Going forward to close the issue.
