### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by ericdrosado** [Portfolio-Shop/portfolioshop#88]
Other than GitHub Topics, your description will be the primary way of catching the users eyes. Your repo description should be clear and concise. Ask yourself:

* In one sentence, how do I convey what my repo does?
* What type of users am I interested in attracting to my repo?
* If I was a user, what words or phrases might spark my interest?

> This is an open source portfolio management system. 

This is a good start, but what is a "portfolio management system?" When I see "portfolio management," I think this repo will manage my stock portfolio versus my brand portfolio. What can we do to make this clear for other students?

**Comment by sudip-mondal-2002** [comment]
Hi @ericdrosado sir, I have updated the project description. Once have a look and let me know if any changes are needed.

**Comment by ericdrosado** [comment]
@sudip-mondal-2002 this is a great start! It's a bit long, so let's try to make this concise. 

Your last sentences get to the heart of what your repo is trying to accomplish. 

Perhaps it could be:

`portfolioshop builds custom portfolio websites with submitted user data`

What do you think? Do you think this captures exactly what your project does? Are we missing any keywords?

**Comment by sudip-mondal-2002** [comment]
Hi @ericdrosado, it was great fit in there, I've put this in the repo description

**Comment by ericdrosado** [comment]
@sudip-mondal-2002 I would recommend just using `portfolioshop builds custom portfolio websites with submitted user data` as your description. The description, as is, is very long.

**Comment by sudip-mondal-2002** [comment]
Yes sir, done. Thank you.
