### ISSUE TITLE
Move or Change Save button

### ISSUE THREAD

**Issue by Mikadifo** [Portfolio-Shop/portfolioshop#95]
**Is your feature request related to a problem? Please describe.**
I didn't see the the save button at the first sight, when I finally saw it, I thought it was a footer button, so I had to scroll to know that button was to save the information.

**Describe the solution you'd like**
I'd like the button to be changed as a static one or move up to be more visible for the user.
I think it's perfect for mobile devices but for web I think is better a button at the end of the form as usual.

**Additional context**
I was looking for the button in the red rectangle section as in many other forms.
<img width="1376" alt="Screen Shot 2022-05-23 at 3 45 38 PM" src="https://user-images.githubusercontent.com/51935560/169894664-5ce452b1-9f26-4ba3-863e-531af0abf5f1.png">

**Comment by singharyan1007** [comment]
Hii , i would like to work on this issue, so can you assign me this one?

**Comment by sudip-mondal-2002** [comment]
Yes sure @singharyan1007, make sure you follow the contribution guidelines.

**Comment by singharyan1007** [comment]
hii @sudip-mondal-2002 can you guide me through the azure setup as I am much familiar with the gcp.

**Comment by sudip-mondal-2002** [comment]
Can you please check the contribution.md file once? After that if you have any doubts, please open a chat in the discussion forum.

**Comment by sudip-mondal-2002** [comment]
@singharyan1007 I am going to unassign you as there is no response for a long time, if you still want to contribute please let us know in this thread.

**Comment by 3swayam** [comment]
@sudip-mondal-2002  Can you share your lower env configurations ? I would like to work on this as well as few other issues. Thanks

**Comment by sudip-mondal-2002** [comment]
I'm sharing the keys, can't share the values due to security reasons. Inside the `/api` directory create a file named `local.settings.json`. Azure-related services can be built using the azure portal on the internet or if you want to use your device, use the Azure CLI to generate blob services and optionally MongoDB database too. You may optionally leave some environment depending on the issue you're working on.
```js
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "",
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "MONGO_LINK": "Link to the MongoDB database",
    "AZURE_BLOB_CONNECTION_STRING": "Connection string to the blob storage",
    "AZURE_BLOB_URL": "Url to the azure blob container",
    "REACT_APP_GOOGLE_AUTH_CLIENT_ID": "Client ID from google cloud console",
    "HOST": "http://localhost:7071"
  }
}
```

**Comment by mohdaakib** [comment]
@sudip-mondal-2002 can u please assign me this issues ?

**Comment by its-ayush-07** [comment]
@sudip-mondal-2002 can I work on this issue under hacktoberfest?

**Comment by sudip-mondal-2002** [comment]
@its-ayush-07 sure please go ahead
